# addon grafana configuration
#
grafana:
  enabled: true

# addon prometheus configuration
#
prometheus:
  enabled: true

# addon servicegraph configuration
#
servicegraph:
  enabled: true

# addon jaeger tracing configuration
#
tracing:
  enabled: true

# addon kiali tracing configuration
#
kiali:
  enabled: true
  dashboard:
    jaegerURL: http://jaeger-quey:16686
    grafanaURL: http://grafana:3000
  kialiuserkey:
  kialipasskey:
  createLoginSecret: true
# Istio CNI plugin enabled
#   This must be enabled to use the CNI plugin in Istio.  The CNI plugin is installed separately.
#   If true, the privileged initContainer istio-init is not needed to perform the traffic redirect
#   settings for the istio-proxy.
#
istio_cni:
  enabled: true

# addon Istio CoreDNS configuration
#
istiocoredns:
  enabled: true

